apiVersion: v1
kind: Service
metadata:
  name: kserve-webhook-server-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    control-plane: kserve-controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: kserve-controller-manager-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 8443
    targetPort: https
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: modelmesh-serving
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: modelmesh-controller
    app.kubernetes.io/managed-by: modelmesh-controller
    app.kubernetes.io/name: modelmesh-controller
spec:
  type: ClusterIP
  selector:
    modelmesh-service: modelmesh-serving
  ports:
  - name: grpc
    port: 8033
    protocol: TCP
    targetPort: grpc
  - name: http
    port: 8008
    protocol: TCP
    targetPort: http
  - name: prometheus
    port: 2112
    protocol: TCP
    targetPort: prometheus
